import UIKit

struct Airline {
    
    let image: String
    let name: String
}

/* let unsortedAirlines = [Airline(image: "FL", name: "Southwest"),
             Airline(image: "DL", name: "Delta"),
             Airline(image: "FR", name: "Ryanair"),
             Airline(image: "UA", name: "United"),
             Airline(image: "AA", name: "American"),
             Airline(image: "AK", name: "AirAsia"),
             Airline(image: "U2", name: "easyJet"),
             Airline(image: "NH", name: "All Nippon"),
             Airline(image: "QR", name: "Qatar"),
             Airline(image: "EK", name: "Emirates"),
             Airline(image: "JL", name: "Japan Airlines"),
             Airline(image: "6E", name: "IndiGo"),
             Airline(image: "W6", name: "Wizz Air"),
             Airline(image: "9C", name: "Spring Airlines"),
             Airline(image: "B6", name: "jetBlue"),
             Airline(image: "BA", name: "British Airways"),
             Airline(image: "LH", name: "Lufthansa"),
             Airline(image: "TK", name: "Turkish Airlines"),
             Airline(image: "4C", name: "LATAM"),
             Airline(image: "CZ", name: "China Southern"),
             Airline(image: "AS", name: "Alaska Airlines"),
             Airline(image: "NK", name: "Spirit Airlines"),
             Airline(image: "SU", name: "Aeroflot"),
             Airline(image: "KL", name: "KLM"),
             Airline(image: "CX", name: "Cathay Pacific"),
             Airline(image: "VY", name: "Vueling"),
             Airline(image: "DY", name: "Norwegian"),
             Airline(image: "AC", name: "Air Canada"),
             Airline(image: "9W", name: "Jet Airways"),
             Airline(image: "IB", name: "Iberia"),
             Airline(image: "AF", name: "Air France"),
             Airline(image: "F9", name: "Frontier Airlines"),
             Airline(image: "EY", name: "Etihad Airways"),
             Airline(image: "G9", name: "Air Arabia"),
             Airline(image: "5J", name: "Cebu Pacific"),
             Airline(image: "SQ", name: "Singapore"),
             Airline(image: "SV", name: "Saudia"),
             Airline(image: "QF", name: "Qantas"),
             Airline(image: "FM", name: "Shanghai"),
             Airline(image: "MU", name: "China Eastern"),
             Airline(image: "AZ", name: "Alitalia"),
             Airline(image: "AI", name: "Air India"),
             Airline(image: "4U", name: "Eurowings"),
             Airline(image: "MH", name: "Malaysia"),
             Airline(image: "KE", name: "Korean Air")] */

    let unsortedAirlines = [Airline(image: "FL", name: "Southwest"),
                Airline(image: "DL", name: "Delta"),
                Airline(image: "FR", name: "Ryanair"),
                Airline(image: "UA", name: "United"),
                Airline(image: "AA", name: "American Airlines"),
                Airline(image: "AK", name: "AirAsia"),
                Airline(image: "U2", name: "easyJet"),
                Airline(image: "NH", name: "All Nippon"),
                Airline(image: "QR", name: "Qatar Airways"),
                Airline(image: "EK", name: "Emirates"),
                Airline(image: "JL", name: "Japan Airlines"),
                Airline(image: "6E", name: "IndiGo Airlines"),
                Airline(image: "W6", name: "Wizzair"),
                Airline(image: "9C", name: "Spring Airlines"),
                Airline(image: "B6", name: "JetBlue"),
                Airline(image: "BA", name: "British Airways"),
                Airline(image: "LH", name: "Lufthansa"),
                Airline(image: "TK", name: "Turkish Airlines"),
                Airline(image: "4C", name: "LATAM"),
                Airline(image: "CZ", name: "China Southern"),
                Airline(image: "AS", name: "Alaska Airlines"),
                Airline(image: "NK", name: "Spirit"),
                Airline(image: "SU", name: "Aeroflot"),
                Airline(image: "KL", name: "KLM"),
                Airline(image: "CX", name: "Cathay Pacific"),
                Airline(image: "VY", name: "Vueling Airlines"),
                Airline(image: "DY", name: "Norwegian Air Shuttle"),
                Airline(image: "AC", name: "Air Canada"),
                Airline(image: "9W", name: "Jet Airways"),
                Airline(image: "IB", name: "Iberia"),
                Airline(image: "AF", name: "Air France"),
                Airline(image: "F9", name: "Frontier"),
                Airline(image: "EY", name: "Etihad"),
                Airline(image: "G9", name: "Air Arabia"),
                Airline(image: "5J", name: "Cebu Pacific"),
                Airline(image: "SQ", name: "Singapore Airlines"),
                Airline(image: "SV", name: "Saudia"),
                Airline(image: "QF", name: "Qantas"),
                Airline(image: "FM", name: "Shanghai Airlines"),
                Airline(image: "MU", name: "China Eastern"),
                Airline(image: "AZ", name: "Alitalia"),
                Airline(image: "AI", name: "Air India"),
                Airline(image: "4U", name: "Eurowings"),
                Airline(image: "MH", name: "Malaysia Airlines"),
                Airline(image: "KE", name: "Korean Air")]

//return sorted array
let airlines = unsortedAirlines.sorted { ($0.name, $0.image) < ($1.name, $0.image)}
